---
language: go
sudo: false
notifications:
  email: false
go:
  - 1.8.x
  - master
jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    - stage: test
      before_install:
        - go get -u github.com/golang/dep/cmd/dep
      before_script:
        - dep ensure
      script: go test -race -v $(go list ./... | grep -v /vendor/) 
