[[constraint]]
  branch = "master"
  name = "github.com/brutella/hc"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/gosexy/to"

[[constraint]]
  branch = "master"
  name = "github.com/oleksandr/bonjour"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
