[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"
