[[constraint]]
  branch = "master"
  name = "github.com/brutella/hc"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gosexy/to"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
